AWS_ACCESS_KEY_ID: AKIAIB5IS2YAUZQR2XRA
AWS_SECRET_ACCESS_KEY: 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
development:
  SENDGRID_USERNAME: app18969372@heroku.com
  SENDGRID_PASSWORD: xpia9jj6
  AWS_BUCKET: sbloccit-development
  FACEBOOK_ID: 1380353822187089
  FACEBOOK_SECRET: 00495260e641fdf657faae382b496097
production:
  AWS_BUCKET: sbloccit-production
  FACEBOOK_ID: 209837255864352
  FACEBOOK_SECRET: 544428ac3112495765ca2650e5faaad0